name: CI - Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-gi \
          python3-gi-cairo \
          gir1.2-gtk-3.0 \
          gir1.2-webkit2-4.1 \
          libfuse2 \
          wget
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGObject
        
    - name: Test Python script
      run: |
        # Test that the main script has no syntax errors
        python3 -m py_compile whatsapp.py
        echo "✅ Python script syntax OK"
        
    - name: Verify GTK dependencies
      run: |
        python3 -c "import gi; gi.require_version('Gtk', '3.0'); gi.require_version('WebKit2', '4.1'); from gi.repository import Gtk, WebKit2; print('✅ GTK dependencies OK')"
        
    - name: Test build script
      run: |
        chmod +x build-appimage-simple.sh
        # Do a dry run to check if the script works without actually building
        bash -n build-appimage-simple.sh
        echo "✅ Build script syntax OK"
        
    - name: Check required files
      run: |
        files=("whatsapp.py" "whatsapp.desktop" "build-appimage-simple.sh" "README.md")
        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file missing"
            exit 1
          fi
        done
