name: Multi-Distro Build Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM UTC

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        python-version: ['3.9', '3.10', '3.11']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-gi \
          python3-gi-cairo \
          gir1.2-gtk-3.0 \
          gir1.2-webkit2-4.1 \
          libfuse2 \
          wget
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGObject
        
    - name: Test compatibility
      run: |
        python3 -c "
        import sys
        print(f'Python version: {sys.version}')
        import gi
        gi.require_version('Gtk', '3.0')
        gi.require_version('WebKit2', '4.1')
        from gi.repository import Gtk, WebKit2
        print('✅ All dependencies work on ${{ matrix.os }} with Python ${{ matrix.python-version }}')
        "
        
    - name: Quick build test
      run: |
        chmod +x build-appimage-simple.sh
        # Test the dependency check part of the script
        bash -c 'source build-appimage-simple.sh && echo "Dependency check passed"' || echo "Build script needs adjustment for this environment"
